version: '2'

services:

  apanaj_optimizer-video:
    networks:
      - video-network
      - network-front-proxy

networks:
  video-network:
  network-front-proxy:
    external:
      name: frontproxy_front-network
