version: '2'

services:

  apanaj_optimizer_video:
    build:
      context: .
      dockerfile: Dockerfile
    image: apanaj_optimizer_video
      expose:
      ## On Private Network
        - "80"
    networks:
      - video-network
      - network-front-proxy

networks:
  video-network:
  network-front-proxy:
    external:
      name: frontproxy_front-network
