version: '2'

volumes:
  vol-mongodb:
    #### - /data/db
  vol-mongodb-log:
    #### - /var/log/mongodb/
  vol-optimizer-data:
    #### - /data/vids/
  vol-share:

services:

  apanaj_optimizer-video:
    build:
      context: ./
      dockerfile: Dockerfile
    image: apanaj_optimizer-video
    expose:
      - "80"
    environment:
      - SECRET_KEY=zx8^qa7j[5go[o0?&/kTu88
      - MONGO_HOST=opt-storage-mongo
      - MONGO_PORT=27017
      - CELERY_BROKER_URL=pyamqp://opt-rabbitmq
      - CELERY_RESULT_BACKEND=redis://opt-redis
      - MEDIA_FOLDER=/data/vids/
      - SERVER_HOST=apanaj_optimizer-video
    volumes:
     - ./project/:/project
     - vol-optimizer-data:/data/vids/
     - vol-share:/v-share/


  opt-storage-mongo:
    image: mongo:3.4.0
    expose:
     - "27017"
    volumes:
     - vol-mongodb:/data/db/
     - vol-mongodb-log:/var/log/mongodb/
     - vol-share:/v-share/

  opt-redis:
    image: redis:4.0.2-alpine
    expose:
     - "6379"
    volumes:
     - vol-share:/v-share/

  opt-rabbitmq:
    image: rabbitmq:3.6.14-alpine
    expose:
     - "5672"
    volumes:
     - vol-share:/v-share/

